<?php

/* @var $block Magento\Framework\View\Element\Template */

?>

<div class="dm-row flex justify-center" id="question-button-click">
    <div class="col-md-6 col-xs-12 fake-col margin-box">
        <button class="action secondary-custom width-full"
                data-bind="click: createQuestion"
        >
            <span class="text text--uppercase"><?= __('Fai la tua domanda') ?></span>
        </button>
    </div>
</div>